#!/bin/bash

########################################################################
########################################################################
#
#       Faust Docker Wrapper Script
#       (GRAME / Y. Orlarey)
#
#       This script simplifies the usage of the Faust compiler
#       running in a Docker container.
#
########################################################################
########################################################################

IMAGE="ghcr.io/orlarey/faustdocker:main"

if ! docker image inspect "$IMAGE" &> /dev/null; then docker pull "$IMAGE"; fi

docker run --rm -v "$PWD:/tmp" "$IMAGE" "$@"
