#!/bin/bash

########################################################################
########################################################################
#
#       Faust Docker Wrapper Script
#       (Y. Orlarey)
#
#       This script simplifies the usage of the Faust compiler
#       running in a Docker container.
#
########################################################################
########################################################################

IMAGE="ghcr.io/orlarey/faustdocker:main"
docker run --rm -v "$PWD:/tmp" "$IMAGE" "$@"
